### ISSUE TITLE
hash0.pw dead

### ISSUE THREAD

**Issue by weedy** [dannysu/hash0#3]
Sites down

**Comment by dannysu** [comment]
You can `git clone` this repo and open the `index.html` in a browser. It's the same thing as what's hosted on hash0.pw.

For now the site should be back to working state. But I'm going to shutdown hash0.pw for good soon. I'll give it couple more months.

**Comment by weedy** [comment]
Have you moved on from this? Is there something better I should use for passwords?

**Comment by dannysu** [comment]
Yeah, unfortunately I no longer have time to maintain it.

I'm now using [KeepassXC](https://github.com/keepassxreboot/keepassxc)
