### ISSUE TITLE
RNG changed in new browsers?

### ISSUE THREAD

**Issue by weedy** [dannysu/hash0#4]
I know you dropped this but I'm hoping it's an easy fix.
https://github.com/dannysu/hash0/blob/3293de5888b144d293f8fc40abe9b085e4088d46/app/js/controllers.js#L73

Now that I've updated to firefox-50.1.x and chrome 55.0.2883.75 I can't decrypt anything anymore.
The firefox addon KINDA works but only picks up a couple passwords I have saved.

**Comment by dannysu** [comment]
I took a quick look, but I really don't have time to spare at the moment. I forgot about the sjcl dependency when I migrated from my old web host. However, even after adding that it's still not quite working for me.

Try it out and see if it's working for you.

If not, I suggest that you run the app locally so you can recover your password.

The steps are:

1. git clone the repo
2. git submodule update --init
3. Run a web server from the root directory (E.g. python -m SimpleHTTPServer)
4. Use a browser and go to http://127.0.0.1:8000 (or wherever your web server serves from)
